// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbq0XLbtU68bvG1wxuHEkQ4A0q0xNJrdA',
    appId: '1:281655354801:web:b3aa447a526ec2f4f44990',
    messagingSenderId: '281655354801',
    projectId: 'salon-groom-app',
    authDomain: 'salon-groom-app.firebaseapp.com',
    storageBucket: 'salon-groom-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc_pFuWkXZiZDCW69r2UoFX-8tW-nbCNo',
    appId: '1:281655354801:android:9efa6ebae38dd375f44990',
    messagingSenderId: '281655354801',
    projectId: 'salon-groom-app',
    storageBucket: 'salon-groom-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmGT32nviq1pXi33yYWStJU7yj_wVg3w4',
    appId: '1:281655354801:ios:a06390fe540a13eef44990',
    messagingSenderId: '281655354801',
    projectId: 'salon-groom-app',
    storageBucket: 'salon-groom-app.appspot.com',
    iosClientId: '281655354801-9smao91acdquv3nivhnddh9r8aeu5ur4.apps.googleusercontent.com',
    iosBundleId: 'com.example.salonOwner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmGT32nviq1pXi33yYWStJU7yj_wVg3w4',
    appId: '1:281655354801:ios:a06390fe540a13eef44990',
    messagingSenderId: '281655354801',
    projectId: 'salon-groom-app',
    storageBucket: 'salon-groom-app.appspot.com',
    iosClientId: '281655354801-9smao91acdquv3nivhnddh9r8aeu5ur4.apps.googleusercontent.com',
    iosBundleId: 'com.example.salonOwner',
  );
}
